#!/bin/bash
#SBATCH -J on2logic_case_study
#SBATCH --time=12:00:00
#SBATCH -A LEE-SL3-CPU
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=wjm41@cam.ac.uk
##SBATCH --no-requeue
#SBATCH -p cclake

. /etc/profile.d/modules.sh
module purge
module load rhel7/default-ccl
module load miniconda/3
source activate cdh

cd /home/wjm41/ml_physics/CDH
python on2logic/case_study.py -path_to_case_study_items=data/case_study_list.txt
